experiment:
  id: get_real_item
  output_base_dir: ./experiments/get_real_item/
  create_timestamp_dir: true

retrieval:
  method: hybrid          # 檢索方法，選擇 'tfidf', 'bm25', 'dense', 或 'hybrid'
  hybrid_alpha: 0.5       # hybrid 模式下 dense/sparse score 的融合比例，範圍 0~1，越高越偏重 dense
  dense_model: all-MiniLM-L6-v2  # Dense 檢索使用的 SentenceTransformer 模型名稱（Hugging Face）

data:
  input_path: dataset/input.pkl        # 輸入的使用者 query 字典（pickle 格式）
  articles_csv: dataset/articles_mapping.csv   # 商品描述的資料（包含 prod_name 與 detail_desc）
  mapping_path: dataset/article_to_idx.pkl  # article_id 對應至系統內部編號的 mapping

output:
  result_path: dataset/output.pkl
  enable_detailed_log: true              # 是否啟用每筆 mapping 詳細 log
  detailed_log_filename: retrieval_log.json  # log 檔案名稱（會自動放在 log_dir 下）


device:
  cuda_visible_devices: "0"  # 指定使用的 GPU id，若使用 dense/hybrid 模式建議配置 GPU
