retrieval:
  method: hybrid          # 檢索方法，選擇 'tfidf', 'bm25', 'dense', 或 'hybrid'
  hybrid_alpha: 0.5       # hybrid 模式下 dense/sparse score 的融合比例，範圍 0~1，越高越偏重 dense
  dense_model: all-MiniLM-L6-v2  # Dense 檢索使用的 SentenceTransformer 模型名稱（Hugging Face）

data:
  input_path: data/input.pkl        # 輸入的使用者 query 字典（pickle 格式）
  articles_csv: data/articles.csv   # 商品描述的資料（包含 prod_name 與 detail_desc）
  mapping_path: data/article_to_idx.pkl  # article_id 對應至系統內部編號的 mapping

output:
  result_path: results/output.pkl       # 輸出的結果 pickle
  log_path: results/retrieval_log.json  # 儲存每筆查詢對應的商品（可選，用於 debug 或分析）

device:
  cuda_visible_devices: "0"  # 指定使用的 GPU id，若使用 dense/hybrid 模式建議配置 GPU

experiment:
  tag: retrieve_0531_hybrid    # 本次實驗的標記或名稱，可用於識別輸出資料夾等
